import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import {
  parseReleasePrepareArguments,
  prepareReleaseVersion,
  updateCargoLockWorkspaceVersions,
  updateCargoWorkspaceVersion,
  validateReleaseVersion,
} from "../../scripts/release/prepare-version.mjs";

async function createRepositoryFixture() {
  const root = await mkdtemp(path.join(os.tmpdir(), "codexhost-release-version-"));
  await writeFile(
    path.join(root, "package.json"),
    `${JSON.stringify({ name: "codexhost", version: "0.0.0", private: true }, null, 2)}\n`,
  );
  await writeFile(
    path.join(root, "package-lock.json"),
    `${JSON.stringify(
      {
        name: "codexhost",
        version: "0.0.0",
        lockfileVersion: 3,
        packages: {
          "": { name: "codexhost", version: "0.0.0" },
          "packages/example": { name: "@codexhost/example", version: "0.0.0" },
        },
      },
      null,
      2,
    )}\n`,
  );
  await mkdir(path.join(root, "crates/example/src"), { recursive: true });
  await writeFile(
    path.join(root, "Cargo.toml"),
    `[workspace]\nmembers = ["crates/example"]\nresolver = "3"\n\n[workspace.package]\nversion = "0.0.0"\nedition = "2024"\n`,
  );
  await writeFile(
    path.join(root, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "codexhost-example"\nversion = "0.0.0"\n`,
  );
  await writeFile(
    path.join(root, "crates/example/Cargo.toml"),
    `[package]\nname = "codexhost-example"\nversion.workspace = true\nedition.workspace = true\n`,
  );
  await writeFile(path.join(root, "crates/example/src/lib.rs"), "pub fn example() {}\n");
  return root;
}

async function readJson(filePath) {
  return JSON.parse(await readFile(filePath, "utf8"));
}

describe("release version preparation", () => {
  it("accepts positional and named semver versions", () => {
    expect(parseReleasePrepareArguments(["0.2.0"])).toEqual({
      help: false,
      version: "0.2.0",
    });
    expect(parseReleasePrepareArguments(["--version=0.3.0-beta.1"])).toEqual({
      help: false,
      version: "0.3.0-beta.1",
    });
    expect(parseReleasePrepareArguments(["--version", "0.3.0-test.1"])).toEqual({
      help: false,
      version: "0.3.0-test.1",
    });
  });

  it("rejects missing, placeholder, and malformed release versions", () => {
    expect(() => parseReleasePrepareArguments([])).toThrow("release version is required");
    expect(() => validateReleaseVersion("0.0.0")).toThrow("must not be 0.0.0");
    expect(() => validateReleaseVersion("01.2.3")).toThrow("must be valid semver");
    expect(() => validateReleaseVersion("1.2")).toThrow("must be valid semver");
    expect(() => parseReleasePrepareArguments(["0.2.0", "0.2.1"])).toThrow(
      "unknown release prepare argument",
    );
  });

  it("updates the product and Cargo workspace versions and reports the matching tag", async () => {
    const root = await createRepositoryFixture();
    try {
      const prepared = await prepareReleaseVersion({ root, version: "0.2.0-beta.1" });
      expect(prepared).toEqual({
        changedFiles: ["package.json", "package-lock.json", "Cargo.toml", "Cargo.lock"],
        tag: "v0.2.0-beta.1",
        version: "0.2.0-beta.1",
      });

      const manifest = await readJson(path.join(root, "package.json"));
      const lockfile = await readJson(path.join(root, "package-lock.json"));
      const cargoManifest = await readFile(path.join(root, "Cargo.toml"), "utf8");
      const cargoLock = await readFile(path.join(root, "Cargo.lock"), "utf8");
      expect(manifest.version).toBe("0.2.0-beta.1");
      expect(lockfile.version).toBe("0.2.0-beta.1");
      expect(lockfile.packages[""].version).toBe("0.2.0-beta.1");
      expect(lockfile.packages["packages/example"].version).toBe("0.0.0");
      expect(cargoManifest).toContain('version = "0.2.0-beta.1"');
      expect(cargoLock).toContain('version = "0.2.0-beta.1"');
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("only replaces the version in the Cargo workspace package section", () => {
    const source = `[workspace]\nmembers = []\n\n[workspace.package]\nversion = "0.0.0"\n\n[profile.release]\ncodegen-units = 1\n`;
    expect(updateCargoWorkspaceVersion(source, "1.2.3")).toBe(
      `[workspace]\nmembers = []\n\n[workspace.package]\nversion = "1.2.3"\n\n[profile.release]\ncodegen-units = 1\n`,
    );
    expect(() => updateCargoWorkspaceVersion("[workspace]\nmembers = []\n", "1.2.3")).toThrow(
      "must define [workspace.package]",
    );
  });

  it("updates only Cargo.lock packages reported as workspace members", () => {
    const source = `version = 4\n\n[[package]]\nname = "codexhost-example"\nversion = "0.0.0"\n\n[[package]]\nname = "third-party"\nversion = "0.0.0"\nsource = "registry+https://example.invalid"\n`;
    expect(updateCargoLockWorkspaceVersions(source, new Set(["codexhost-example"]), "1.2.3")).toBe(
      `version = 4\n\n[[package]]\nname = "codexhost-example"\nversion = "1.2.3"\n\n[[package]]\nname = "third-party"\nversion = "0.0.0"\nsource = "registry+https://example.invalid"\n`,
    );
  });

  it("is idempotent when the requested version is already prepared", async () => {
    const root = await createRepositoryFixture();
    try {
      await prepareReleaseVersion({ root, version: "0.2.0" });
      await expect(prepareReleaseVersion({ root, version: "0.2.0" })).resolves.toEqual({
        changedFiles: [],
        tag: "v0.2.0",
        version: "0.2.0",
      });
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });

  it("refuses to update a lockfile for a different root package", async () => {
    const root = await createRepositoryFixture();
    try {
      const lockPath = path.join(root, "package-lock.json");
      const lockfile = await readJson(lockPath);
      lockfile.packages[""].name = "other-product";
      await writeFile(lockPath, `${JSON.stringify(lockfile, null, 2)}\n`);
      await expect(prepareReleaseVersion({ root, version: "0.2.0" })).rejects.toThrow(
        "root package name does not match",
      );
      expect((await readJson(path.join(root, "package.json"))).version).toBe("0.0.0");
    } finally {
      await rm(root, { recursive: true, force: true });
    }
  });
});
